edit.php SQL statement done
timothyoei/cop4331_small_project pull request #13
Opened 2022-09-05 16:02 UTC by Osvy789

Add.php done and edit.php almost done

2022-09-05 22:06 UTC, timothyoei commented
Can you split this commit so the endpoints that don't work (i.e., edit and delete) aren't added yet? We don't want to merge unfinished code into main as it's our "working" copy

2022-09-05 22:10 UTC, timothyoei requested changes

2022-09-05 22:10 UTC, timothyoei commented on api/add.php
> +    $addSQL = $dbConn->prepare("INSERT INTO Contacts (LastName, FirstName, Email, Phone, Address, Zip, City, State, ContactID, UserID) VALUES ('" . $LastName . "','" . $FirstName . "','" . $Email . "
Appending a bunch of values like this into a one-liner isn't very readable. Can you refactor this?

2022-09-05 22:10 UTC, timothyoei commented on api/add.php
> +$LastName = $inData['LastName'];
We only access these properties once in the sql statement so no need to create variables for each one

2022-09-06 18:41 UTC, timothyoei requested changes

2022-09-06 18:41 UTC, timothyoei commented on api/delete.php
> +    $deleteSQL = $dbConn->prepare("DELETE FROM Contacts WHERE contactID= '" . $ContactID . "', UserID='" . $UserID . "'");
Does this work on the server? You might need to add an AND in that WHERE

2022-09-06 18:41 UTC, timothyoei commented on api/delete.php
> +      throw new Exception("Could Not Insert Record");
Change this error message to be more descriptive of what failed?

2022-09-06 18:41 UTC, timothyoei commented on api/edit.php
> +    $editSQL = $dbConn->prepare("UPDATE Contacts SET LastName='" . $LastName . "', FirstName= '" . $FirstName . "', Email= '" . $Email . "', Phone='" . $Phone . "', Address= '" . $Address . "', Zip=
Same as above comments

2022-09-06 18:41 UTC, timothyoei commented on api/edit.php
> +      throw new Exception("Could Not Insert Record");
Same as previous error comment

2022-09-07 22:40 UTC, timothyoei requested changes

2022-09-07 22:40 UTC, timothyoei commented on api/search.php
> +  $searchSQL = $dbConn->prepare("SELECT firstName, lastName FROM Contacts WHERE firstName LIKE ? OR lastName LIKE ?");
Fixed in this [pr](https://github.com/timothyoei/cop4331_small_project/pull/14)

2022-09-07 22:40 UTC, timothyoei commented on api/edit.php
> +                                AND WHERE contactID= '" . $ContactID . "', UserID='" . $UserID ."'");
AND goes inside the WHERE (e.g., WHERE ContactID = $ContactID AND UserID = $UserID) <--- NOT the solution

2022-09-07 22:40 UTC, timothyoei commented
@Osvy789 Can you add a test plan/screenshots of this code working on the server with postman? Take a look at the previous api pr's for examples

2022-09-08 17:32 UTC, timothyoei commented
Let's wait until after the demo to make changes to the api. You'll also need to fix the merge conflict as #14 went in

2022-09-08 19:15 UTC, Osvy789 commented on api/add.php
> +$LastName = $inData['LastName'];
I know I just did it because it helps me in the implementing the variables at least it makes it easier.

2022-09-09 21:21 UTC, timothyoei approved these changes

2022-09-10 14:41 UTC, timothyoei approved these changes

2022-09-10 21:48 UTC, timothyoei approved these changes

2022-09-10 22:12 UTC, merged